services:
  app:
    build: .
    container_name: link-shortener
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY_EMAIL=${SECRET_KEY_EMAIL}
      - SECRET_KEY_TELEGRAM=${SECRET_KEY_TELEGRAM}
    depends_on:
      - db
      - redis
    logging:
      options:
        max-size: 5m

  db:
    image: postgres:16.8-alpine3.21
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 5m

  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    volumes:
      - ./redis_data:/data
    logging:
      options:
        max-size: 5m

  worker:
    build: .
    container_name: worker
    command: celery -A tasks.process.celery_app worker --loglevel=info
    depends_on:
      - app
      - redis
    logging:
      options:
        max-size: 5m

  test_db:
    image: postgres:16.8-alpine3.21
    container_name: test_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: test_${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./test_postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
